blank_issues_enabled: false
contact_links:
  - name: WordPress.org Support Forum
    url: https://wordpress.org/support/plugin/the-simplest-importer/
    about: For general support questions, please use the WordPress.org support forum.
